### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Julien-Broyard/agence-voyage#1]
Hi again @Julien-Broyard  here's what I came up with your Agence-Voyage project! I hope you like it! 
![PRES-01](https://user-images.githubusercontent.com/36028424/55821264-a7e67680-5b2f-11e9-85fa-a4a7b1777dd1.png)

**Comment by Julien-Broyard** [comment]
As always a meaningful and beautiful logo, thanks for the work :tada: :smile:

**Comment by Tobaloidee** [comment]
Awesome! Will finish the files now 👍😄

**Comment by Tobaloidee** [comment]
Hi @Julien-Broyard  here's the PR #2 with the logo upload & readme update! later today i will share you the link to my drive for the other versions. Have a great day!

**Comment by Tobaloidee** [comment]
Thanks @Julien-Broyard  :) what does your type-graphql-api project do?

**Comment by Julien-Broyard** [comment]
Nothing really useful since it was made only for learning purposes :laughing:

**Comment by Tobaloidee** [comment]
I will design for it also @Julien-Broyard  😃

**Comment by Julien-Broyard** [comment]
Thank you :smile:

**Comment by Tobaloidee** [comment]
I finished the design @Julien-Broyard  Its there in the issue page of the project. :)

**Comment by Tobaloidee** [comment]
@Julien-Broyard  here's the link to the other versions of AGENCY-VOYAGE's logo..I forgot to give you..You can download it [HERE](https://drive.google.com/drive/u/0/folders/1fceACiZITS1CRDolSguiJX9cVB1s_t3H) 😊👍 Thanks again!
